server:
  port: 8080
spring:
  application:
    name: main-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true