server:
  port: 8080
spring:
  application:
    name: main-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  cloud:
    config:
      fail-fast: false
  config:
    import: "optional:configserver:http://localhost:8888"
  graphql:
    graphiql:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rab
    password: 1234
    directExchangeName: main.direct.exchange
audit_booking:
  queue:
    name: booking-events
    routingKey: audit
document_verification:
  queue:
    name: documentVerificationQueue
    routingKey: document.verify