services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      RABBITMQ_DEFAULT_USER: rab
      RABBITMQ_DEFAULT_PASS: 1234
      RABBITMQ_DEFAULT_VHOST: vhost
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq￼
    ports:
      - "5672:5672"
      - "15672:15672"

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=audits
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=1234

  audit-log-service:
    image: nawm77/audit-log-service
    build:
      context: ../../audit-log-service/Dockerfile
    container_name: audit-log-service
    ports:
      - "8081:8081"
    restart: unless-stopped